#!/usr/bin/env bash
# Configure ssh client public key authentication and other settings
Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredential no
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
